### ISSUE TITLE
Experiment Data Logging

### ISSUE THREAD

**Issue by MickyHoltzman** [Anna4142/PrisonerDilemmaPy#10]
I think some changes to the logged data are required:
1) Add decision and reward data to the "return abort" trials (the failure happed after the decision made and reward given)
2) delete the hard coded reward numbers. We should use the actual reward parameters (either time or, better yet, micro-litters)
3) Second step - add additional info per system spec (such as, experiment configuration, mouse ID, actual decision and return times, etc..

**Comment by Anna4142** [comment]
1.will add it
2.i removed in ml because i use the logger file later in the analysis script and there its better to have numbers
3.this seems like relevant information to add.should I add it?

**Comment by MickyHoltzman** [comment]
So, it seems we agree on the changes, and need to decide who will do it :-)
I added some comments on the system requirement discussion which seems to be redundant. I forgot I opened another issue specific to the logger. Can you please ask ben if he has more ideas? I am sure he had thought about it a lot on his other projects.

As to who is doing what: I feel you have your hands full will the video analyzer, learners and data analysis. I suggest that I will be responsible for all other modules (logger included). But, its really up to you. If you want to do the logger (and experiment manager - for the decision time capturing) changes you are quite welcome :-). Do not hesitate to let me do it, though. Its quite all right.

**Comment by Anna4142** [comment]
alright you can make the relevant changes to the logger and if any issues come up we will discuss them

**Comment by MickyHoltzman** [comment]
Will do.
