### ISSUE TITLE
Error in reward center

### ISSUE THREAD

**Issue by Anna4142** [Anna4142/PrisonerDilemmaPy#27]
hello

i get htis erro not all the time for center reward delivery but randomly at times.Can you think why that is?It is referring to the deliver_reward function in the RewardManager.py file

  File "C:\Users\EngelHardBlab.MEDICINE\Downloads\PrisonerDilemmaPy_(4)\PrisonerDilemmaPy\Reward_manager\RewardManager.py", line 24, in deliver_reward
    self.valves[valveindex].OpenValve(reward_time)
TypeError: list indices must be integers or slices, not NoneType

**Comment by MickyHoltzman** [comment]
I think I know what's going on. 

So, first thing first. The problem:
MouseMonitor is trying to deliver reward to Location.Unknown. The reward manager does not find the valve and is trying to open valve[None]. Hence the error. 

Second, why did it happen:
MouseMonitor is delivering the reward to its current location - which is set the last time GetDecision() was invoked. So between the time it was in the Center and the reward decision was made, the mouse left the center position and its current location is Unknown. Obviously, I did not expect this to happen, so the SW is not considering this scenario and fails. My bed :-)

And here is issues:
Look at the State diagram please. After the decision reward is delivered the system transitions to WaitForCenter state. Once the mouse is in center the system transitions to TrialComplete and than to CenterReward. Two State transitions require at least two cycles on the main loop in the ExperimentManager which means the mouse locations is verified again and it has a chance to get out of center position. However the transition to CenterReward is happening regardless of mouse location hence the error.

Now, this is only one loop cycle which takes a few milliseconds if not less (in the microseconds range). How did the mouse leave center so quickly? I think this is a video detection error. It was never there, or just pocked its nose in, or something. Next time it happens look at the video, try to figure out how did it get out of Center so quickly.

Regardless the unconditional transition from TrialCompleted to CenterReward is not clean. I am emailing you a change proposal for the state diagram. Let's discuss it on Thursday. 

Temporary solution (already implemented in RewardManager): Check if valveindex is Null and set to mouse 1 Center valve (Arduino channel 4).

**Comment by Anna4142** [comment]
ok will wait for it

**Comment by Anna4142** [comment]
i think it should be an event based transition where we wait for them to come to center.what do you think

**Comment by MickyHoltzman** [comment]
problem solved
